In [48]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
import re
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.neural_network import MLPRegressor

In [3]:
magnet_positions_df = pd.read_csv("../../data/magnet_dataset_x_positions.csv", index_col=0)
magnet_positions_df

,Feature_0,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_191,Feature_192,Feature_193,Feature_194,Feature_195,Feature_196,Feature_197,Feature_198,Feature_199,phenotype
0,-14.560726,-29.174853,-30.219015,-20.703540,-27.245609,-6.855496,-29.970324,-37.541994,-13.723348,4.978868,...,-2.625085,-35.895294,-24.132941,-15.285674,-5.001560,-15.194465,-28.097855,-22.069756,-13.362686,1.620004
1,-23.660365,-14.238357,-1.218080,-19.879584,-39.776027,-27.457098,-29.717173,-1.433078,-19.108184,-1.022080,...,-4.513075,-12.624437,-38.697442,-24.210011,-22.065143,-12.662580,-33.274614,-33.156084,-22.141083,0.000000
2,-33.835094,4.398591,-34.336234,-19.833219,-8.572251,-33.040140,-19.435081,-12.193901,-19.538961,-37.781793,...,-37.518731,-24.464410,-27.024110,-27.686923,-12.833227,-14.032880,-15.703531,-2.578970,-4.681123,0.756617
3,-0.750988,-22.669432,-20.370383,-11.911836,-18.859337,-36.930333,-13.999532,-37.434460,4.583349,-29.814671,...,-20.520564,-10.940225,-3.471428,-18.504450,-24.950003,-26.293561,-39.101160,-20.010713,-31.679717,6.274446
4,-29.926937,-9.012730,-10.429397,-13.298132,4.085019,-0.286924,-2.483403,-26.672612,-1.920923,-3.859997,...,-3.770522,-10.945585,-27.071284,-16.145115,-37.480422,-15.897819,-7.226805,-26.497660,-31.643722,1.490994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-2.213484,-37.483021,-11.551698,4.194093,-5.288259,4.978758,-8.458777,-4.329105,-27.917666,-9.963139,...,-38.038837,3.224699,-8.068871,-26.441692,-32.346926,-35.660695,-35.913751,-21.491766,-10.112239,0.941450
996,-9.924243,-18.654299,-32.432225,-38.075925,-29.481543,-39.303074,-2.423658,-2.997648,-15.166713,-34.435691,...,-32.873735,-6.924580,-34.517070,-36.344467,4.553065,-37.895821,-3.334510,-26.082293,3.824667,1.922898
997,-4.510743,0.574865,-7.985110,-37.484152,-18.435795,-8.159112,-35.900718,-22.960154,-36.290558,4.812556,...,-31.485256,-27.044965,-39.480744,-13.185172,-1.468561,-14.865670,-7.897504,-28.406538,-22.015801,2.087176
998,-37.177201,-11.484056,-34.506324,-38.354191,2.187943,-27.200052,-8.571678,-4.144284,1.363796,-3.455352,...,-31.911241,-15.856280,-16.178337,-28.515094,3.645680,-16.156567,-32.213821,-8.449480,-2.512097,3.140595
999,-17.603909,-24.414830,0.033227,-15.359969,-11.392819,-20.807722,-29.379491,-22.490111,-16.516609,-39.612022,...,-37.679030,-11.866198,-27.743466,-16.271644,-31.092615,-28.390418,-18.006934,-10.734585,-6.340304,2.082542

In [4]:
magnet_polarizations_df = pd.read_csv("../../data/magnet_dataset_polarisation.csv", index_col=0)
magnet_polarizations_df

,Feature_0,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_191,Feature_192,Feature_193,Feature_194,Feature_195,Feature_196,Feature_197,Feature_198,Feature_199,phenotype
0,2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.620004
1,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,1.0,0.000000
2,2.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.756617
3,2.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,2.0,6.274446
4,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.490994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.0,2.0,0.0,0.0,2.0,1.0,1.0,0.941450
996,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.922898
997,2.0,0.0,1.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,...,2.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,2.087176
998,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,3.140595
999,2.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.082542

In [6]:
best_training_features = pd.read_csv("../../data/best_features_magnet.csv", index_col=0)
best_training_features

        features
0     Feature_92
1     Feature_39
2     Feature_97
3     Feature_54
4    Feature_137
..           ...
171   Feature_62
172   Feature_63
173   Feature_57
174   Feature_65
175  Feature_121

[176 rows x 1 columns]

In [7]:
PHENOTYPE_COL = "phenotype"
XY = magnet_positions_df
y = XY[PHENOTYPE_COL]
X = XY.drop(PHENOTYPE_COL, axis=1)

In [11]:
def extract_list(input_string):
    extracted_strings = re.findall(r"'(.*?)'", input_string)
    return extracted_strings

all_genes = best_training_features
all_genes = list(all_genes["features"].values)

In [19]:
causal_features = [179, 198, 12, 18, 144]

In [50]:
NUM_ITERATIONS = 100
n_features_for_regression = 10
NUM_HOLDOUT_SAMPLES = 20

mae_list = []
feature_combination_list = []
update_here = []

best_mae = np.inf
best_gene_set = None

models = [LinearRegression(),
          Ridge(),
          Lasso(),
          ElasticNet(),
          SVR(),
          DecisionTreeRegressor(),
          RandomForestRegressor(),
          GradientBoostingRegressor(),
          KNeighborsRegressor(),
          xgb.XGBRegressor(),
          lgb.LGBMRegressor(),
          MLPRegressor()
          ]
model_results = []

for model in models:

    # print("Start search")
    for j in range(NUM_ITERATIONS):
        choose_n = best_training_features.sample(n=n_features_for_regression).values.flatten()
        X_only_n = X[choose_n]
        holdout_sample_mae_list = []
        update = 0
        for k in range(NUM_HOLDOUT_SAMPLES):
            X_train, X_test, y_train, y_test = train_test_split(X_only_n, y, test_size=0.33)
            model = model
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            mae = mean_absolute_error(y_test, y_pred)
            holdout_sample_mae_list.append(mae)
        mean_mae = np.mean(holdout_sample_mae_list)

        ## Uncomment to monitor progress
        if mean_mae < best_mae:
            # print(mean_mae)
            best_mae = mean_mae
            update = 1
            best_gene_set = choose_n
        # if j % 1000 == 0:
        #     print(j)
        update_here.append(update)
        mae_list.append(mean_mae)
        feature_combination_list.append(choose_n)

    #print(f"End step 3. Best score {best_mae:.4f} with genes:")
    for gene in best_gene_set:
        print(gene)

    result_df = pd.DataFrame()
    result_df["MAE"] = mae_list
    result_df["Features"] = feature_combination_list
    result_df["Update"] = update_here
    result_df.to_csv("result_unsorted_magnet.csv")

    df = pd.read_csv("result_unsorted_magnet.csv", index_col=0)

    ave_mae_list = []
    covered_genes = []
    for gene in all_genes:
        focal_gene = gene
        focal_gene_count = 0
        mae_sum = 0
        for index, row in df.iterrows():
            features = extract_list(row["Features"])
            mae = row["MAE"]
            if focal_gene in features:
                focal_gene_count += 1
                mae_sum += mae

        if focal_gene_count > 0:
            average_mae = mae_sum/focal_gene_count
            ave_mae_list.append(average_mae)
            covered_genes.append(focal_gene)
        else:
            print(f"Gene {focal_gene} not covered")

    result_df = pd.DataFrame()
    result_df["Gene"] = covered_genes
    result_df["ave_MAE"] = ave_mae_list

    pred = list(result_df.sort_values("ave_MAE").head(5)["Gene"])
    pred = set([int(element.split("_")[1]) for element in pred])
    true = set(causal_features)
    intersection = true.intersection(pred)
    union = true.union(pred)
    jaccard = len(intersection)/len(union)

    model_results.append(jaccard)

Feature_19
Feature_108
Feature_17
Feature_193
Feature_80
Feature_10
Feature_179
Feature_125
Feature_122
Feature_198
Feature_199
Feature_179
Feature_88
Feature_15
Feature_190
Feature_106
Feature_144
Feature_97
Feature_59
Feature_135
Feature_107
Feature_113
Feature_144
Feature_85
Feature_161
Feature_5
Feature_12
Feature_162
Feature_170
Feature_43
Feature_102
Feature_60
Feature_152
Feature_179
Feature_170
Feature_12
Feature_71
Feature_30
Feature_144
Feature_181
Feature_102
Feature_60
Feature_152
Feature_179
Feature_170
Feature_12
Feature_71
Feature_30
Feature_144
Feature_181
Feature_102
Feature_60
Feature_152
Feature_179
Feature_170
Feature_12
Feature_71
Feature_30
Feature_144
Feature_181
Feature_102
Feature_60
Feature_152
Feature_179
Feature_170
Feature_12
Feature_71
Feature_30
Feature_144
Feature_181
Feature_102
Feature_60
Feature_152
Feature_179
Feature_170
Feature_12
Feature_71
Feature_30
Feature_144
Feature_181
Feature_102
Feature_60
Feature_152
Feature_179
Feature_170
Feature_12
Feature_71
Feature_30
Feature_144
Feature_181

In [35]:
pred = list(result_df.sort_values("ave_MAE").head(5)["Gene"])
pred = set([int(element.split("_")[1]) for element in pred])
pred

{12, 54, 124, 144, 179}

In [45]:
pred = list(result_df.sort_values("ave_MAE").head(5)["Gene"])
pred = set([int(element.split("_")[1]) for element in pred])
true = set(causal_features)
intersection = true.intersection(pred)
union = true.union(pred)
jaccard = len(intersection)/len(union)

In [46]:
jaccard

0.42857142857142855

In [42]:
pred

{12, 54, 124, 144, 179}

In [43]:
true.intersection(pred)

{12, 144, 179}

In [15]:
result_df

         MAE                                           Features  Update
0   1.171670  [Feature_168, Feature_158, Feature_152, Featur...       1
1   1.201800  [Feature_155, Feature_24, Feature_88, Feature_...       0
2   1.184419  [Feature_160, Feature_63, Feature_1, Feature_4...       0
3   1.193895  [Feature_135, Feature_185, Feature_14, Feature...       0
4   1.198262  [Feature_93, Feature_192, Feature_86, Feature_...       0
..       ...                                                ...     ...
95  1.190251  [Feature_66, Feature_123, Feature_25, Feature_...       0
96  1.147982  [Feature_123, Feature_192, Feature_120, Featur...       0
97  1.156718  [Feature_24, Feature_9, Feature_41, Feature_15...       0
98  1.178193  [Feature_175, Feature_85, Feature_63, Feature_...       0
99  1.192546  [Feature_94, Feature_184, Feature_125, Feature...       0

[100 rows x 3 columns]